#!/usr/bin/env sh

git checkout master
git pull
yarn config set version-tag-prefix "release/"
yarn config set version-git-message "[release][ci skip] prepare release/%s"
yarn version
version=$(node -e "console.log(require('./package.json').version)")
git push origin master
git push origin "release/$version"
npm publish --access public
